### ISSUE TITLE
Restrict subscription by location

### ISSUE THREAD

**Issue by luisarnauth** [josunefon/Scripts#1]
https://github.com/josunefon/Scripts/blob/c2176fae84eb59f4f42cb4e30d177b86d2775376/AZ_Runbook_AzureQuotasAndLimitsToLA.ps1#L59

We need to restrict the resources to the current subscription, or else we will always have all locations from all subscriptions :)

```powershell
$locations = Search-AzGraph -Query "Resources | where subscriptionId == '$($subscription.Id)' | distinct location"
```

**Comment by josunefon** [comment]
Fixed
