### ISSUE TITLE
Count of Role Assignments not returning expected results

### ISSUE THREAD

**Issue by luisarnauth** [josunefon/Scripts#2]
https://github.com/josunefon/Scripts/blob/63614954affa05cdee0198e25900fb8ec8feb56d/AZ_Runbook_AzureQuotasAndLimitsToLA.ps1#L98

Apparently running the above command in Azure Cloud Shell and Azure Automation returns different results :(

The code below will return the expected results, aligned with what is showed in Azure Portal

```powershell
$RoleAssignments = (Get-AzRoleAssignment -Scope "/subscriptions/$($subscription.Id)" | Where-Object {$_.Scope -Like "/subscriptions/$($subscription.Id)*"}).count
```
Issue found and solved by @ludovicbonivert 💪

**Comment by josunefon** [comment]
Thanks @ludovicbonivert :)
